version: '3'
services:
  nextjs:
    build:
      context: ./nextjs
    volumes:
      - ./nextjs:/nextjs
      - node_modules:/nextjs/node_modules
    ports:
      - 3000:3000
    tty: true
    init: true

  gin:
    build:
      context: ./gin
    volumes:
      - ./gin:/gin
    ports:
      - 8080:8080
    tty: true
    init: true

  # terraform:
  #   image: hashicorp/terraform:1.4
  #   volumes:
  #     - ./terraform:/terraform
  #   entrypoint: ash
  #   tty: true
  #   init: true
  #   env_file:
  #     - .env

volumes:
  node_modules:
